" BASIC SETUP:

" enter the current millenium
set nocompatible

" enable syntax, plugins (for netrw) and indentation
syntax enable
filetype plugin indent on
set autoindent

" Setting up the tabs from the Vim wiki on reddit
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab

" omnifunc settings
au FileType python setl ofu=pythoncomplete#CompletePython

" FINDING FILES:

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu

" NOW WE CAN:
" - Hit tab to :find by partial match
" - Use * to make it fuzzy

" THINGS TO CONSIDER:
" - :b lets you autocomplete any open buffer

" FILE BROWSING:

" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" NOW WE CAN:
" - :edit a folder to open a file browser
" - <CR>/v/t to open in an h-split/v-split/tab
" - check |netrw-browse-maps| for more mappings

" MISCELLANEOUS:

" highlight matching [{()}]
set showmatch

" show line numbers
set number

" improve text search inside a file
set incsearch
set hlsearch

" code folding
set foldenable
set foldlevelstart=10
set foldmethod=syntax

" Have lines wrap instead of continue off-screen
set linebreak

" Gives Vim access to a broader range of colours
set termguicolors

" set dark colours for the terminal
hi Terminal ctermbg=black ctermfg=white guibg=black guifg=white

" KEY MAPPINGS
" In order,
" mapped <SPACE> as the <Leader>
" mapped :q!<CR> to <Leader>q
" mapped :wq<CR> to <Leader>wq
" mapped :w<CR> to <Leader>w
" mapped :vert term<CR> to <Leader>t
" mapped :vert help<CR> to <Leader>vh

" copied a command from a reddit comment to invoke the help command with an
" argument, but vertically

" copied a command from stack overflow: https://vi.stackexchange.com/a/18455
" to check higlighting group for a word

let g:mapleader=" "

cnoremap <Leader>q :q!<CR>
cnoremap <Leader>wq :wq<CR>
cnoremap <Leader>w :w<CR>
cnoremap <Leader>vt :vert term<CR>
cnoremap <Leader>vh :vert help<CR>

command! -nargs=? -complete=help Vh vert help <args>
command Hid  echo synIDattr(synID(line("."), col("."), 1), "name")
